package org.totogames.infoengine.rendering.opengl.enums;

import static org.lwjgl.opengl.GL46C.*;

public enum TextureDataType {
    UNSIGNED_BYTE(GL_UNSIGNED_BYTE),
    BYTE(GL_BYTE),
    UNSIGNED_SHORT(GL_UNSIGNED_SHORT),
    SHORT(GL_SHORT),
    UNSIGNED_INT(GL_UNSIGNED_INT),
    INT(GL_INT),
    HALF_FLOAT(GL_HALF_FLOAT),
    FLOAT(GL_FLOAT),
    UNSIGNED_BYTE_3_3_2(GL_UNSIGNED_BYTE_3_3_2),
    UNSIGNED_BYTE_2_3_3_REV(GL_UNSIGNED_BYTE_2_3_3_REV),
    UNSIGNED_SHORT_5_6_5(GL_UNSIGNED_SHORT_5_6_5),
    UNSIGNED_SHORT_5_6_5_REV(GL_UNSIGNED_SHORT_5_6_5_REV),
    UNSIGNED_SHORT_4_4_4_4(GL_UNSIGNED_SHORT_4_4_4_4),
    UNSIGNED_SHORT_4_4_4_4_REV(GL_UNSIGNED_SHORT_4_4_4_4_REV),
    UNSIGNED_SHORT_5_5_5_1(GL_UNSIGNED_SHORT_5_5_5_1),
    UNSIGNED_SHORT_1_5_5_5_REV(GL_UNSIGNED_SHORT_1_5_5_5_REV),
    UNSIGNED_INT_8_8_8_8(GL_UNSIGNED_INT_8_8_8_8),
    UNSIGNED_INT_8_8_8_8_REV(GL_UNSIGNED_INT_8_8_8_8_REV),
    UNSIGNED_INT_10_10_10_2(GL_UNSIGNED_INT_10_10_10_2),
    UNSIGNED_INT_2_10_10_10_REV(GL_UNSIGNED_INT_2_10_10_10_REV),
    UNSIGNED_INT_24_8(GL_UNSIGNED_INT_24_8),
    UNSIGNED_INT_10F_11F_11F_REV(GL_UNSIGNED_INT_10F_11F_11F_REV),
    UNSIGNED_INT_5_9_9_9_REV(GL_UNSIGNED_INT_5_9_9_9_REV),
    FLOAT_32_UNSIGNED_INT_24_8_REV(GL_FLOAT_32_UNSIGNED_INT_24_8_REV);

    private final int value;

    TextureDataType(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
