package org.totogames.infoengine.rendering.opengl.enums.texparams;

import static org.lwjgl.opengl.GL46C.*;

public enum TextureLevelParameter {
    TEXTURE_WIDTH(GL_TEXTURE_WIDTH),
    TEXTURE_HEIGHT(GL_TEXTURE_HEIGHT),
    TEXTURE_DEPTH(GL_TEXTURE_DEPTH),
    TEXTURE_SAMPLES(GL_TEXTURE_SAMPLES),
    TEXTURE_FIXED_SAMPLE_LOCATIONS(GL_TEXTURE_FIXED_SAMPLE_LOCATIONS),
    TEXTURE_INTERNAL_FORMAT(GL_TEXTURE_INTERNAL_FORMAT),
    TEXTURE_RED_SIZE(GL_TEXTURE_RED_SIZE),
    TEXTURE_GREEN_SIZE(GL_TEXTURE_GREEN_SIZE),
    TEXTURE_BLUE_SIZE(GL_TEXTURE_BLUE_SIZE),
    TEXTURE_ALPHA_SIZE(GL_TEXTURE_ALPHA_SIZE),
    TEXTURE_DEPTH_SIZE(GL_TEXTURE_DEPTH_SIZE),
    TEXTURE_STENCIL_SIZE(GL_TEXTURE_STENCIL_SIZE),
    TEXTURE_SHARED_SIZE(GL_TEXTURE_SHARED_SIZE),
    TEXTURE_ALPHA_TYPE(GL_TEXTURE_ALPHA_TYPE),
    TEXTURE_DEPTH_TYPE(GL_TEXTURE_DEPTH_TYPE),
    TEXTURE_COMPRESSED(GL_TEXTURE_COMPRESSED),
    TEXTURE_COMPRESSED_IMAGE_SIZE(GL_TEXTURE_COMPRESSED_IMAGE_SIZE),
    TEXTURE_BUFFER_DATA_STORE_BINDING(GL_TEXTURE_BUFFER_DATA_STORE_BINDING),
    TEXTURE_BUFFER_OFFSET(GL_TEXTURE_BUFFER_OFFSET),
    TEXTURE_BUFFER_SIZE(GL_TEXTURE_BUFFER_SIZE);

    private final int value;

    TextureLevelParameter(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
