package org.totogames.infoengine.rendering.opengl.enums.texparams;

import static org.lwjgl.opengl.GL46C.*;

public enum TextureParameter {
    TEXTURE_BASE_LEVEL(GL_TEXTURE_BASE_LEVEL),
    TEXTURE_BORDER_COLOR(GL_TEXTURE_BORDER_COLOR),
    TEXTURE_COMPARE_MODE(GL_TEXTURE_COMPARE_MODE),
    TEXTURE_COMPARE_FUNC(GL_TEXTURE_COMPARE_FUNC),
    TEXTURE_LOD_BIAS(GL_TEXTURE_LOD_BIAS),
    TEXTURE_MAG_FILTER(GL_TEXTURE_MAG_FILTER),
    TEXTURE_MAX_LEVEL(GL_TEXTURE_MAX_LEVEL),
    TEXTURE_MAX_LOD(GL_TEXTURE_MAX_LOD),
    TEXTURE_MIN_FILTER(GL_TEXTURE_MIN_FILTER),
    TEXTURE_MIN_LOD(GL_TEXTURE_MIN_LOD),
    TEXTURE_SWIZZLE_R(GL_TEXTURE_SWIZZLE_R),
    TEXTURE_SWIZZLE_G(GL_TEXTURE_SWIZZLE_G),
    TEXTURE_SWIZZLE_B(GL_TEXTURE_SWIZZLE_B),
    TEXTURE_SWIZZLE_A(GL_TEXTURE_SWIZZLE_A),
    TEXTURE_SWIZZLE_RGBA(GL_TEXTURE_SWIZZLE_RGBA),
    TEXTURE_WRAP_S(GL_TEXTURE_WRAP_S),
    TEXTURE_WRAP_T(GL_TEXTURE_WRAP_T),
    TEXTURE_WRAP_R(GL_TEXTURE_WRAP_R),
    //DEPTH_TEXTURE_MODE(GL_DEPTH_TEXTURE_MODE),
    //GENERATE_MIPMAP(GL_GENERATE_MIPMAP),
    IMAGE_FORMAT_COMPATIBILITY_TYPE(GL_IMAGE_FORMAT_COMPATIBILITY_TYPE),
    TEXTURE_IMMUTABLE_FORMAT(GL_TEXTURE_IMMUTABLE_FORMAT),
    TEXTURE_IMMUTABLE_LEVELS(GL_TEXTURE_IMMUTABLE_LEVELS),
    TEXTURE_VIEW_MIN_LEVEL(GL_TEXTURE_VIEW_MIN_LEVEL),
    TEXTURE_VIEW_NUM_LEVELS(GL_TEXTURE_VIEW_NUM_LEVELS),
    TEXTURE_VIEW_MIN_LAYER(GL_TEXTURE_VIEW_MIN_LAYER),
    TEXTURE_VIEW_NUM_LAYERS(GL_TEXTURE_VIEW_NUM_LAYERS);

    private final int value;

    TextureParameter(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
